### ISSUE TITLE
father 4 TODOs

### ISSUE THREAD

**Issue by PeachScript** [umijs/father-next#5]
> 为了和 Umi 主版本保持一致 + 此前做过一版纯 esbuild 的 father 3 alpha，所以计划直接发 father 4 了
> father 4 介绍 + 任务集合，欢迎评论参与共建，做之前先认领（编辑主贴，加 @自己 ），避免冲突。

### 核心升级

- 📦 依赖预打包：类似 Umi 3.5/4 的依赖预打包，基于 ncc（打包文件）+ api-extractor（生成类型）
- ⚔️ 双模式构建
  - Bundle 模式：仅 UMD 产物走 bundle 模式，核心从 rollup 换成宽容度更高的 webpack
  - Bundless 模式：ESM/CJS 产物走 bundless 模式 + 生成 TS 类型定义，默认提供 babel（browser）+ esbuild（node）双编译核心，可基于插件系统注册 swc/tsc 模式
- 🏗 工程化能力生成：基于 Umi 4 的 generator，提供打包场景的原子工程化能力，例如 g eslint、g test、g commitlint 等
- 🚨 自动诊断：功能类似 brew doctor，自动对打包场景的常见误区做诊断并给出最佳实践，具备可集成能力（比如集成到 dumi 中）
- 🚧 Friendly Error：统一处理双模式构建中的常见错误，并给出友好提示，提升使用体验 + 降低答疑成本
- 🛫 去历史包袱
  - 去 umi-test 集成，改用微生成器
  - 去 storybook 集成，改和 dumi 集成
  - 去 monorepo 支持，改其他工具替代（pnpm？）
  - 去 rollup 核心，改用 webpack

### 结构图
<img width="980" alt="overview" src="https://user-images.githubusercontent.com/5035925/142365147-5b90d10c-190d-47ad-b7d8-f1b621c8d343.png">

### First-time Tasks（⭐️ 代表预估难度）
- [ ] ⭐️ 完善 `scheme.ts`，father 自身属性都做细致校验，比如 `esm: { overrides: { ... } }` 下只能配什么，三方仍然用 `object` 
- [x] ⭐️ dev 下最后一条日志输出时分秒，便于用户确认编译时间
- -- ↓ 已完成 ↓ --
- [x] ⭐️ 参考 [Umi](https://github.com/umijs/umi/blob/master/packages/umi/src/defineConfig.ts) 实现 `defineConfig`，用于 `.fatherrc.ts` 中补全配置类型 @cnyballk umijs/father-next#15 
- [x] ⭐️ 完善 `version` 命令，分行追加输出 `@vercel/ncc`、`babel`、`esbuild`、`webpack`、`typescript`、`@microsoft/api-extractor` 的版本号，并添加测试用例（mock `console.log`）@xiaohuoni https://github.com/umijs/father-next/pull/14
- [x] ⭐️ `father build` 支持可选 `--no-clean` 参数，构建前不清空输出目录 @xiaohuoni https://github.com/umijs/father-next/pull/12
- [x] ⭐️ `src/types.ts` 里完善 `@todo` 的类型，从 `@umijs/utils/compiled` 和 `@umijs/bundler-utils/compiled` 里找 @zzcan umijs/father-next#17 
- [x] ⭐️ `bundless/index.ts` 里对没匹配到配置的文件输出 debug 日志，使用 `@umijs/utils` 里的 `debug`，命名空间用 `father:bundless` @zzcan umijs/father-next#18 
- [x] ⭐️⭐️ umd 支持 `name` 配置项，配置模块挂载的全局变量名称 @xiaohuoni umijs/father-next#61 
- [x] ⭐️⭐️ `prebundle` 配置项添加顶层的 `output` 配置项 + 去掉 `deps` 内层的 `output` 配置项，并添加用例 @zzcan umijs/father-next#30 
- [x] ⭐️⭐️ `builder/config.ts` 里 `getConfigForFile` 支持自动获取 tsconfig.json 中的 `compilerOptions.paths` 并转换为 `alias`，并添加用例 @xierenyuan umijs/father-next#21 

### RC version related
- [x] 参考 [create-umi](https://github.com/umijs/umi/tree/master/packages/create-umi) 实现 create-father @PeachScript https://github.com/umijs/father-next/commit/9aa4957fcd9a2c50e2b4cb94dd5a1e2cce662ab2
- [x] 推广文章 @PeachScript 

### Release related
- [ ] 指南文档完善 umijs/father-next#68 
  - [ ] 迁移文档
  - [ ] 同类工具比较
  - [ ] FAQ
- [ ] umd 从 `@umijs/bundler-webpack` 开放 `theme` 和 `lessLoader` 配置项
- [ ] 脚手架在 prepublishOnly 脚本里添加 `father doctor` 命令
- [ ] 推广文章

### Core Service

- [x] 初始化仓库，基于 Umi Core 实现配置读取、命令执行、插件注册 @sorrycc b318356
- [x] 用户配置类型定义
- [x] 用户配置 Schema 校验规则 @PeachScript 
- [x] 用户配置支持 `extends` @PeachScript umijs/father-next#11 

### Builder Module

> 做组件库源码打包/编译

- [x] 用户配置转换成 Builder 配置 @PeachScript 
- [ ] 构建执行器 (Executor)
  - [x] bundless 构建执行器 @PeachScript 
  - [x] bundless d.ts 文件生成 @PeachScript https://github.com/umijs/father-next/commit/ca349bec0a41b44ab08e4ed9e8b173091c14b04b
  - [x] bundless watch 模式 @cnyballk umijs/father-next#6 
  - [x] bundle 构建执行器 @PeachScript 
  - [ ] 统一 Error 捕获及输出
  - [x] bundless cjs（由于 PureESM 时机尚早，故仍然提供 cjs 产物） @PeachScript https://github.com/umijs/father-next/commit/d2c7bd5015e9f58c81691952b177acaf13343902
- [x] 基于 webpack loader 的 loader 系统（Bundless）@PeachScript
- [x] 内置 js 转换器 (Bundless Transformer)
  - [x] babel @lylwanan https://github.com/umijs/father-next/commit/c98d1b27fe6e8d25e6bf7b78a438ec522799bb0c
  - [x] esbuild @PeachScript https://github.com/umijs/father-next/commit/86eb61230eea5f86e283643d9f1b902883a55712
- [x] 内置打包器 (Bundler，基于 @umijs/bundler-webpack) @PeachScript https://github.com/umijs/father-next/commit/5c57c80a5a48c2ddeec8d18c7417f4cc2a2746de
- [x] 编译提速
  - [x] Bundless 持久缓存 umijs/father-next#51 
  - [x] Bundle 持久缓存
  - [ ] Babel 持久缓存（Bundless/Bundle 是否存在共用的可能性？）
  - [ ] esbuild 启用增量构建（incremental）

### PreCompile Module

> 做框架/工具的依赖打包，类似 Umi 4

- [x] 用户配置转换 @PeachScript https://github.com/umijs/father-next/commit/44f633fa8780e8c7ff45575cdcb207b3fd266900
- [x] ncc bundler 打包依赖 @PeachScript https://github.com/umijs/father-next/commit/ce496ccf78a3dcc491049e9e612b67182fdcd98e
- [x] api-extractor 生成类型定义 @PeachScript https://github.com/umijs/father-next/commit/225ab46f5d9f5161287395bd9fc225e1a5afaf90
  - [x] 加 patcher 支持 `export =` 语法 @PeachScript https://github.com/umijs/father-next/commit/99bfa645fa2e69c74eb7c8f27947a82db5cb203d
- [ ] 类型打包能力完善 umijs/father-next#28 
- [ ] 预打包产物校验 @siyi98 
  - [ ] 是否包含动态 require 子路径模块的逻辑
  - [ ] …

### 自动化测试
- [x] GitHub CI Action + Coverage @PeachScript umijs/father-next#8 
- [x] Bundle @PeachScript https://github.com/umijs/father-next/commit/cdec059983ac6d5df563be9d5fc35bc2dbf31554
- [x] Bundless @PeachScript 
- [x] PreBundle @PeachScript umijs/father-next#9 
- [x] dev @PeachScript umijs/father-next#10 
- [x] config
- [x] help

### Doctor Module

> 做项目的前置检查，给出研发建议或者错误

umijs/father-next#56 

- [x] 调研/整理
  - [x] father 2 过往 issue 高频问题整理
  - [x] 组件研发场景的最佳实践整理
  - [x] 梳理出前置检查的规则列表（例如无用依赖、package.json 的 sideEffects/main/module/exports 没配对等等） umijs/father#608 
- [x] Rule API 准备
  - [x] `addRegularCheckup` 添加标准检查（用户配置、最终配置、package.json、tsconfig.json 等）
  - [x] `addSourceCheckup` 添加源码检查（源码目录的每一个文件）
  - [x] `addImportsCheckup` 添加 imports 语句检查（`import/await import/require`）
- [x] 研发建议/错误分析及序列化输出
  - [x] 支持控制台输出
  - [ ] 支持 API 调用\供其他框架（例如 dumi）集成到 GUI 中提示开发者

### Generate Module

> 基于 umi g 做原子工程化能力的生成

- [x] 支持生成 jest 配置 @miracles1919 umijs/father-next#66 
- [ ] 支持生成 commitlint 配置 @miracles1919 [#506](https://github.com/umijs/father/pull/506)
- [ ] 支持生成 lint 配置 @miracles1919 

### Changelog

> 类似 ant-design 仓库的 changelog 生成能力，规划中...

- [ ] WIP

**Comment by PeachScript** [comment]
> from https://github.com/umijs/umi-next/issues/187#issuecomment-1023363757
> 让我试试 bundless watch 模式 ？

@cnyballk 抱歉之前消息看漏了，最近还有时间参与吗

**Comment by cnyballk** [comment]
> > from [umijs/umi-next#187 (comment)](https://github.com/umijs/umi-next/issues/187#issuecomment-1023363757)
> > 让我试试 bundless watch 模式 ？
> 
> @cnyballk 抱歉之前消息看漏了，最近还有时间参与吗

可以，整起来

**Comment by PeachScript** [comment]
@cnyballk 那 bundless watch 的你有空先看看方案？大致功能描述：
1. 监听 input 目录的变更，处理文件新增、删除、修改，做增量编译，主要改 `bundless/index.ts`
2. 监听用户配置文件变更，用新的配置对文件做全量编译，主要改 `config.ts`

先看下工作量，如果比较复杂可以再拆子任务我们分一下

**Comment by PeachScript** [comment]
> - [ ] GitHub CI Action + Coverage

@fz6m 现在加了点用例了，这个任务有时间参与吗

**Comment by zzcan** [comment]
有什么小任务能认领的么？

**Comment by PeachScript** [comment]
@zzcan 欢迎加入，正文里加了一类 **First-time Tasks**，可以选择看看

**Comment by cnyballk** [comment]
> 参考 [Umi](https://github.com/umijs/umi/blob/master/packages/umi/src/defineConfig.ts) 实现 defineConfig，用于 .fatherrc.ts 中补全配置类型

我来

**Comment by xierenyuan** [comment]
⭐️⭐️ builder/config.ts 里 getConfigForFile 支持自动获取 tsconfig.json 中的 compilerOptions.paths 并转换为 alias，并添加用例

这个我来

**Comment by PeachScript** [comment]
> ⭐️⭐️ builder/config.ts 里 getConfigForFile 支持自动获取 tsconfig.json 中的 compilerOptions.paths 并转换为 alias，并添加用例
> 
> 这个我来

👍
可以复用 `bundless/dts/index.ts` 里的 `getTsconfig` 方法

**Comment by zzcan** [comment]
⭐️ src/types.ts 里完善 @todo 的类型，从 @umijs/utils/compiled 和 @umijs/bundler-utils/compiled 里找
先认领下这个

**Comment by roc-an** [comment]
加了个油~！

**Comment by siyi98** [comment]
> 预打包产物校验：是否包含动态 require 子路径模块的逻辑

这个我来

**Comment by PeachScript** [comment]
> > 预打包产物校验：是否包含动态 require 子路径模块的逻辑
> 
> 这个我来

👍 有思路的时候先对一下再做？目前的主要参考就是 Umi 4 里打 patch 的 case，都是 ncc 默认没覆盖到的，比如这一段：https://github.com/umijs/umi/blob/master/scripts/bundleDeps.ts#L97-L163

**Comment by siyi98** [comment]
> > > 预打包产物校验：是否包含动态 require 子路径模块的逻辑
> > 
> > 
> > 这个我来
> 
> 👍 有思路的时候先对一下再做？目前的主要参考就是 Umi 4 里打 patch 的 case，都是 ncc 默认没覆盖到的，比如这一段：https://github.com/umijs/umi/blob/master/scripts/bundleDeps.ts#L97-L163

等我梳理一下思路，找你对一下
